version: '3'
services:
    py:
        build: .
        volumes:
            - ./app:/app
            - ./uploads:/uploads
        ports: ["8080:80"]

networks:
    default:
        external:
            name: aiir_network
