version: "3.8"
services:
  builder_head:
    build: .
    image: builder-mpi
    ports:
      - 8080
    depends_on: 
      - builder_worker
    links:
      - builder_worker
    volumes:
      - build-data:/build
    networks:
      - builder-network

  builder_worker:
    build: .
    image: builder-mpi
    volumes:
      - build-data:/build
    networks:
      - builder-network
      
networks:
  net:
    driver: bridge

volumes:
  build-data:

