version: "3.8"
services:
  mpi_head:
    build: .
    ports:
      - 8080
    depends_on: 
      - mpi_node
    links:
      - mpi_node
    volumes:
      - build-data:/build
    networks:
      - net

  mpi_node:
    build: .
    volumes:
      - build-data:/build
    networks:
      - net
      
networks:
  net:
    driver: bridge

volumes:
  build-data:



